name: ID
on:
  workflow_dispatch:
jobs:
  id:
    name: Workflow ID Provider
    runs-on: ubuntu-latest
    steps:
      - name: Echo secret  
        run: echo '${{secrets[env.SECRETNAME]}}'
        env:
          SECRETNAME: TMP

          
        
