name: ID
on:
  workflow_dispatch:
jobs:
  id:
    name: Workflow ID Provider
    runs-on: ubuntu-latest
    steps:
      - name: Echo secret  
        run: |
          secret=$(echo '${{secrets[env.SECRETNAME]}}')
          echo '{"var": "value"}'
          echo $secret
        env:
          SECRETNAME: TMP

          
        
